trilla:
  jwt:
    secret: secret
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/trilla}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    drop-first: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: db/changelog/db.changelog-master.xml
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  security:
    cors:
      allowed-origin-patterns: '*'
      allowed-methods: '*'
      allow-credentials: false
      allowed-headers: '*'
      max-age: 1800
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
